version: "3.6"
volumes:
     shared-workspace:
          name: "hadoop-distributed-file-system"
          driver: local
  
services:
    jupyterlab:
        build: env/jupyterlab
        networks :
              - sparknet
        container_name: mk-jupyter
        ports:
            - 8888:8888
            - 4040:4040
        volumes:
            - shared-workspace:/opt/workspace
            - ./data:/usr/data
            - ./notebooks:/home/jovyan
    spark-master:
        build: env/spark
        networks:
            - sparknet
        environment:
             - SPARK_MODE=master
        container_name: mk-spark-master
        ports:
                - 8080:8080
                - 7077:7077
                - 8998:8998
        volumes:
                - shared-workspace:/opt/workspace
    spark-worker-1:
        build: env/spark
        networks:
                - sparknet
        container_name: mk-spark-worker-1
        environment:
                - SPARK_MODE=worker
                - SPARK_WORKER_CORES=1
                - SPARK_WORKER_MEMORY=512m
        ports:
                - 8081:8081
        volumes:
                - shared-workspace:/opt/workspace
        depends_on:
                - spark-master


networks:
     sparknet:
          name: sparknet
